name: CI Pipeline - main branch only

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install flake8 black isort bandit pip-audit pytest pytest-cov docker

      - name: Lint, Format & Security
        run: |
          black .
          isort .
          flake8 . --max-line-length=120 --ignore=F403,F405
          bandit -r . --severity-level MEDIUM || true
          pip-audit || true

      - name: Run tests with coverage
        run: pytest --cov=tools --cov-fail-under=80

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: app:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Trivy & Scan Image
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget -q https://github.com/aquasecurity/trivy/releases/download/v0.67.2/trivy_0.67.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.67.2_Linux-64bit.deb
          trivy image --scanners vuln --exit-code 0 --severity CRITICAL,HIGH --ignore-unfixed app:latest

      - name: Docker login & push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          [ -z "$DOCKER_USER" ] && echo "❌ Missing DOCKER_USER secret" && exit 1
          [ -z "$DOCKER_PASS" ] && echo "❌ Missing DOCKER_PASS secret" && exit 1
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker tag app:latest dileep1506/python:latest
          docker push dileep1506/python:latest
