name: CI Pipeline - main branch only

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup Python 3.12
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # 3. Install dependencies explicitly (no requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort bandit pip-audit pytest pytest-cov

    # 4. Linting & formatting
    - name: Lint code with flake8
      run: flake8 .

    - name: Check code formatting with black
      run: black --check .

    - name: Check imports with isort
      run: isort . --check-only

    # 5. Security scans
    - name: Run Bandit security scan
      run: bandit -r .

    - name: Run pip-audit dependency scan
      run: pip-audit

    # 6. Unit tests & coverage (minimum 80%)
    - name: Run tests with coverage
      run: pytest --cov=tools --cov-fail-under=80

    # 7. Setup Docker buildx for caching
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 8. Build Docker image
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # 9. Install Trivy for image scanning
    - name: Install Trivy
      run: |
        sudo apt-get update && sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.50.0_Linux-64bit.deb

    # 10. Scan Docker image for vulnerabilities
    - name: Scan Docker image for vulnerabilities
      run: trivy image --exit-code 1 --severity CRITICAL,HIGH app:latest

    # 11. Docker login
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    # 12. Tag and push Docker image to dileep1506/python
    - name: Tag and push Docker image
      run: |
        docker tag app:latest dileep1506/python:latest
        docker push dileep1506/python:latest
