name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: 🧰 Checkout & Setup Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Locate requirements.txt
        id: requirements
        run: |
          if [ -f "requirements.txt" ]; then
            echo "REQ_PATH=requirements.txt" >> $GITHUB_ENV
          elif [ -f "app/requirements.txt" ]; then
            echo "REQ_PATH=app/requirements.txt" >> $GITHUB_ENV
          else
            echo "ERROR: requirements.txt not found in repo root or app/ folder"
            exit 1
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $REQ_PATH

  lint:
    name: 🧼 Linting & Formatting
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install flake8 & autoflake
        run: pip install flake8 autoflake

      - name: Run flake8 lint
        run: flake8 .

      - name: Check formatting with autoflake
        run: autoflake --check --recursive .

  security:
    name: 🔐 Security Scanning (Bandit + Trivy FS)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Bandit scan
        run: |
          pip install bandit
          bandit -r .

      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@v1
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

  test:
    name: 🧪 Unit Testing & Coverage
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install pytest & coverage
        run: pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=my_app --cov-fail-under=80

  build:
    name: 🐳 Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t app:latest .

  image-scan:
    name: 🔎 Scan Docker Image (Trivy)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: app:latest
          format: table
          ignore-unfixed: true
          exit-code: 1
          severity: CRITICAL,HIGH

  push:
    name: 🚀 Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: image-scan
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag & Push Docker image
        run: |
          docker tag app:latest ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
