name: Lint and Trivy Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install flake8 and autoflake
        run: |
          python -m pip install --upgrade pip
          pip install flake8 autoflake

      - name: Auto-fix trailing whitespaces
        run: |
          echo "Removing trailing whitespaces from all Python files..."
          find . -name "*.py" -exec sed -i 's/[ \t]*$//' {} \;

      - name: Auto-fix star imports with autoflake
        run: |
          echo "Replacing star imports with explicit imports (where possible)..."
          find . -name "*.py" -exec autoflake --remove-all-unused-imports --remove-unused-variables --in-place {} \;

      - name: Run Flake8 Linter
        run: |
          echo "Running Python linting..."
          flake8 . --max-line-length=120 --exit-zero

  trivy-scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pythonapp:latest .

      - name: Run container test
        run: docker run --rm pythonapp:latest || echo "Container exited (normal if no long-running process)"

      - name: Scan filesystem with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-path: .
          format: table
          exit-code: 0
          ignore-unfixed: true

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: pythonapp:latest
          format: json
          output: trivy-report.json
          exit-code: 0
          ignore-unfixed: true

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
