name: Python Lint and Trivy Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8

      - name: Run Flake8 Linter
        run: |
          echo "Running Python linting..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  trivy-scan:
    name: Trivy Docker Build & Scan
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image (with args)
        run: |
          docker build \
            --build-arg FROM_IMAGE=python:3.10-slim \
            --build-arg USERNAME=pythonuser \
            -t python-docker-app:latest .

      - name: Run container test
        run: |
          echo "Running container to verify startup..."
          docker run --rm python-docker-app:latest || echo "Container exited (may not have long-running process)"

      - name: Trivy Scan - Filesystem
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-path: .
          format: table
          exit-code: 0
          ignore-unfixed: true

      - name: Trivy Scan - Docker Image (JSON)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: python-docker-app:latest
          format: json
          output: trivy-report.json
          exit-code: 0
          ignore-unfixed: true

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-report.json
